// src/controllers/materialController.js
import Material from "../models/Material.js";

// 📌 Upload study material
export const uploadMaterial = async (req, res) => {
  try {
    const { title, description, subject, gradeLevel, fileUrl } = req.body;

    const material = await Material.create({
      title,
      description,
      subject,
      gradeLevel,
      fileUrl,
      uploadedBy: req.user.id,
    });

    res.status(201).json({ message: "Material uploaded successfully", material });
  } catch (error) {
    res.status(500).json({ message: "Error uploading material", error: error.message });
  }
};

// 📌 Get all materials
export const getMaterials = async (req, res) => {
  try {
    const materials = await Material.find().populate("uploadedBy", "name role");
    res.json(materials);
  } catch (error) {
    res.status(500).json({ message: "Error fetching materials", error: error.message });
  }
};

// 📌 Request material (student request AI-generated)
export const requestMaterial = async (req, res) => {
  try {
    const { topic } = req.body;
    // TODO: integrate with AI
    res.json({ message: `Study material for ${topic} will be generated by AI soon.` });
  } catch (error) {
    res.status(500).json({ message: "Error requesting material", error: error.message });
  }
};
